CREATE SCHEMA STOCKS;
GO


CREATE TABLE STOCKS.TIPO_FORNECEDOR(

	DESIGNACAO	VARCHAR(10),
	CÓDIGO	int	PRIMARY KEY,
);

CREATE TABLE STOCKS.FORNECEDOR(

	NIF	int	PRIMARY KEY,
	ENDERECO	VARCHAR(20) ,
	CONDICOES_DE_PAGAMENTO	VARCHAR(10) NOT NULL,
	FAX	int NOT NULL,
	NOME	VARCHAR(20),
	CÓDIGO_TIPO	int NOT NULL,
	FOREIGN KEY (CÓDIGO_TIPO)	REFERENCES STOCKS.TIPO_FORNECEDOR(CÓDIGO),

);

CREATE TABLE STOCKS.ENCOMENDA(
	NUMERO int	PRIMARY KEY,
	DATA date,
	NIF_FORNECEDOR int NOT NULL,
	FOREIGN KEY (NIF_FORNECEDOR) REFERENCES STOCKS.FORNECEDOR(NIF),
);

CREATE TABLE STOCKS.PRODUTO(
	CODIGO int PRIMARY KEY,
	QUANTIDADE int NOT NULL,
	NOME	VARCHAR(10),
	PRECO DECIMAL(10,2) NOT NULL,
	TAXA_IVA VARCHAR(10),
)

CREATE TABLE STOCKS.ENCOMENDA_TEM_PRODUTOS(
	NUMERO_ENCOMENDA int,
	CODIGO_PRODUTO int,
	UNIDADES int NOT NULL,
	PRIMARY KEY (NUMERO_ENCOMENDA,CODIGO_PRODUTO),
	FOREIGN KEY (NUMERO_ENCOMENDA) REFERENCES STOCKS.ENCOMENDA(NUMERO),
	FOREIGN KEY (CODIGO_PRODUTO) REFERENCES STOCKS.PRODUTO(CODIGO),
);

