CREATE DATABASE aula4
GO

use aula4;
go

CREATE SCHEMA CONFERENCIA;
GO


CREATE TABLE CONFERENCIA.ARTIGO(
	TITULO VARCHAR(15),
	NÚMERO int PRIMARY KEY,
	
);

CREATE TABLE CONFERENCIA.AUTOR(
	EMAIL VARCHAR(15) PRIMARY KEY,
	NOME VARCHAR(15),
	INSTITUIÇÃO VARCHAR(15) NOT NULL,
	
);

CREATE TABLE CONFERENCIA.INSTITUICAO(
	NOME VARCHAR(15),
	ENDEREÇO VARCHAR(15) PRIMARY KEY,
	
);

CREATE TABLE CONFERENCIA.PARTICIPANTE(
	DATA_PRESC DATE,
	NOME VARCHAR(15),
	MORADA VARCHAR(20),
	EMAIL VARCHAR(15) PRIMARY KEY,
	INSTITUIÇAO VARCHAR(15) NOT NULL,
	
);

CREATE TABLE CONFERENCIA.ESTUDANTE(
	EMAIL VARCHAR(15) PRIMARY KEY,
	EC_LOCALIZAÇÃO VARCHAR(15),
	ENDREÇO_INSTITUIÇÃO VARCHAR(15) NOT NULL,

	FOREIGN KEY (ENDREÇO_INSTITUIÇÃO) REFERENCES CONFERENCIA.INSTITUICAO(ENDEREÇO),
);

CREATE TABLE CONFERENCIA.NÃO_ESTUDANTE(
	EMAIL VARCHAR(15) PRIMARY KEY,
	REFERENCIA int NOT NULL,
	ENDEREÇO_INSTITUIÇÃO VARCHAR(15) NOT NULL,

	FOREIGN KEY (ENDEREÇO_INSTITUIÇÃO) REFERENCES CONFERENCIA.INSTITUICAO(ENDEREÇO),
	
);

CREATE TABLE CONFERENCIA.TEM(
	NUMERO_ARTIGO int,
	EMAIL_AUTOR VARCHAR(15),

	PRIMARY KEY (NUMERO_ARTIGO,EMAIL_AUTOR),

	FOREIGN KEY (NUMERO_ARTIGO) REFERENCES CONFERENCIA.ARTIGO(NÚMERO),
	FOREIGN KEY (EMAIL_AUTOR) REFERENCES CONFERENCIA.AUTOR(EMAIL),
	
);